export const ADD_SCOLLEGE = 'ADD_SCOLLEGE';
export const SCOLLEGE_SUCCESS = 'SCOLLEGE_SUCCESS';
export const SCOLLEGE_LOADING = 'SCOLLEGE_LOADING';
export const SCOLLEGE_FAILED = 'SCOLLEGE_FAILED';
export const ADD_GCOLLEGE = 'ADD_GCOLLEGE';
export const GCOLLEGE_SUCCESS = 'GCOLLEGE_SUCCESS';
export const GCOLLEGE_LOADING = 'GCOLLEGE_LOADING';
export const GCOLLEGE_FAILED = 'GCOLLEGE_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const MRANKPREDICT_SUCCESS = 'MRANKPREDICT_SUCCESS';
export const MRANKPREDICT_LOADING = 'MRANKPREDICT_LOADING';
export const MRANKPREDICT_FAILED = 'MRANKPREDICT_FAILED';
export const ARANKPREDICT_SUCCESS = 'ARANKPREDICT_SUCCESS';
export const ARANKPREDICT_LOADING = 'ARANKPREDICT_LOADING';
export const ARANKPREDICT_FAILED = 'ARANKPREDICT_FAILED';
export const SCOLLEGEPREDICT_SUCCESS = 'SCOLLEGEPREDICT_SUCCESS';
export const SCOLLEGEPREDICT_LOADING = 'SCOLLEGEPREDICT_LOADING';
export const SCOLLEGEPREDICT_FAILED = 'SCOLLEGEPREDICT_FAILED';
export const GCOLLEGEPREDICT_SUCCESS = 'GCOLLEGEPREDICT_SUCCESS';
export const GCOLLEGEPREDICT_LOADING = 'GCOLLEGEPREDICT_LOADING';
export const GCOLLEGEPREDICT_FAILED = 'GCOLLEGEPREDICT_FAILED';
export const GRADECONVERT_SUCCESS = 'GRADECONVERT_SUCCESS';
export const GRADECONVERT_LOADING = 'GRADECONVERT_LOADING';
export const GRADECONVERT_FAILED = 'GRADECONVERT_FAILED';


export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const COLLEGE_LIST_REQUEST = "COLLEGE_LIST_REQUEST";
export const COLLEGE_LIST_SUCCESS = "COLLEGE_LIST_SUCCESS";
export const COLLEGE_LIST_FAIL = "COLLEGE_LIST_FAIL";

export const COLLEGE_DETAILS_REQUEST = "COLLEGE_DETAILS_REQUEST";
export const COLLEGE_DETAILS_SUCCESS = "COLLEGE_DETAILS_SUCCESS";
export const COLLEGE_DETAILS_FAIL = "COLLEGE_DETAILS_FAIL";

export const COLLEGE_DELETE_REQUEST = "COLLEGE_DELETE_REQUEST";
export const COLLEGE_DELETE_SUCCESS = "COLLEGE_DELETE_SUCCESS";
export const COLLEGE_DELETE_FAIL = "COLLEGE_DELETE_FAIL";

export const COLLEGE_CREATE_REQUEST = "COLLEGE_CREATE_REQUEST";
export const COLLEGE_CREATE_SUCCESS = "COLLEGE_CREATE_SUCCESS";
export const COLLEGE_CREATE_FAIL = "COLLEGE_CREATE_FAIL";
export const COLLEGE_CREATE_RESET = "COLLEGE_CREATE_RESET";

export const COLLEGE_UPDATE_REQUEST = "COLLEGE_UPDATE_REQUEST";
export const COLLEGE_UPDATE_SUCCESS = "COLLEGE_UPDATE_SUCCESS";
export const COLLEGE_UPDATE_FAIL = "COLLEGE_UPDATE_FAIL";
export const COLLEGE_UPDATE_RESET = "COLLEGE_UPDATE_RESET";